const ROLE_CONFIG = {
  Player:{icon:'🏃',subtitle:'PLAYER',stats:[['Matches','0','Matches played'],['Wins','0','Wins recorded'],['Teams','0','Teams joined'],['Achievements','0','Achievements']],actions:[['⚽','Find Matches','Explore upcoming games and challenges.'],['👥','My Teams','View and manage your teams.'],['📈','Performance','Track your progress and results.']],modules:[['MATCHES','Upcoming matches','No matches scheduled yet. Match scheduling will appear here.'],['PERFORMANCE','Performance overview','Your match results, stats and progress will appear here.'],['ACHIEVEMENTS','Achievements','Complete matches and activities to build your sports record.']]},
  Coach:{icon:'🧑‍🏫',subtitle:'COACH',stats:[['Teams','0','Teams managed'],['Players','0','Players coached'],['Sessions','0','Training sessions'],['Wins','0','Team wins']],actions:[['👥','My Teams','Manage your teams and squad members.'],['🏋️','Training','Plan training sessions and drills.'],['📊','Performance','Review team and player performance.']],modules:[['TEAM MANAGEMENT','Team overview','Your teams, players and squad management will appear here.'],['TRAINING','Training planner','Create and manage upcoming training sessions.'],['TEAM PERFORMANCE','Performance overview','Track team results and individual player progress.']]},
  Organizer:{icon:'📅',subtitle:'ORGANIZER',stats:[['Events','0','Events created'],['Participants','0','Registered participants'],['Tournaments','0','Tournaments'],['Matches','0','Matches scheduled']],actions:[['📅','Create Event','Plan your next sports event.'],['🏆','Tournaments','Manage tournaments and fixtures.'],['📍','Venues','Manage venues and locations.']],modules:[['EVENTS','Events management','Create events, manage registrations and track participation.'],['TOURNAMENTS','Tournament management','Fixtures, teams, rounds and standings will appear here.'],['VENUES','Venue management','Add and manage sports venues for your events.']]},
  Referee:{icon:'🧑‍⚖️',subtitle:'REFEREE',stats:[['Assigned','0','Assigned matches'],['Completed','0','Completed matches'],['Results','0','Results confirmed'],['Cards','0','Cards recorded']],actions:[['📋','Assigned Matches','View matches assigned to you.'],['🕒','Schedule','Check your officiating schedule.'],['📝','Match Management','Enter scores, cards, fouls and match notes.']],modules:[['ASSIGNED MATCHES','Next assignments','No matches are assigned yet. Assigned games will appear here.'],['MATCH MANAGEMENT','Manage a match','Record score, cards, fouls, incidents and match statistics.'],['HISTORY','Refereeing history','Completed matches and confirmed results will appear here.']]}
};
const $=id=>document.getElementById(id); const currentRole=document.body.dataset.role; const config=ROLE_CONFIG[currentRole]; let SERVER_USER=null;
function getUser(){return SERVER_USER}
async function loadCurrentUser(){try{const r=await fetch('/api/auth/me');if(!r.ok)throw new Error();const d=await r.json();SERVER_USER=d.user;return SERVER_USER}catch(e){window.location.href='index.html';return null}}
function render(){if(!config||!SERVER_USER)return;$('sideName')&&($('sideName').textContent=SERVER_USER.full_name||'Member');$('dashboardName')&&($('dashboardName').textContent=SERVER_USER.full_name||'SportHub Member');$('headerName')&&($('headerName').textContent=SERVER_USER.full_name||'Member');$('dashboardRole')&&($('dashboardRole').textContent=currentRole);$('roleDescription')&&($('roleDescription').textContent=({Player:'Manage matches, teams, performance and your sports profile from one place.',Coach:'Manage teams, players, training plans and team performance from one place.',Organizer:'Create events and tournaments, manage participants, venues and fixtures.',Referee:'Manage assigned matches, officiating schedules, scores, incidents and results.'})[currentRole]||'');}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST'})}catch(e){}localStorage.removeItem('sporthubSession');localStorage.removeItem('sporthubUser');localStorage.removeItem('scUser');window.location.href='index.html'}
window.addEventListener('DOMContentLoaded',async()=>{const u=await loadCurrentUser();if(u)render()});
